#!/bin/bash
: '
vi 2-my_filter_states.py
vi 3-my_safe_filter_states.py
vi 4-cities_by_state.py
vi 5-filter_cities.py
vi model_state.py
vi 7-model_state_fetch_all.py
vi 8-model_state_fetch_first.py
vi 9-model_state_filter_a.py
vi 10-model_state_my_get.py
vi 11-model_state_insert.py
vi 12-model_state_update_id_2.py
vi 13-model_state_delete_a.py
vi model_city.py
vi 14-model_city_fetch_by_state.py
'
vi 2-my_filter_states.py
i
#!/usr/bin/python3
:wq!
